name: Devcontainer

on:
  push:
    paths:
      - '.devcontainer/Dockerfile'
  workflow_dispatch:
    
jobs:
  dev-container:
    defaults:
      run:
        shell: bash
        working-directory: .devcontainer/
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v6

    - name: Docker Build
      shell: bash
      run: |
        IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}/challenge
        TAG=$(date +%Y%m%d.$GITHUB_RUN_NUMBER)
        docker build . -t $IMAGE:TAG -t $IMAGE:latest
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker Publish
      shell: bash
      run: |
        docker push -a ghcr.io/${GITHUB_REPOSITORY,,}/challenge