name: Docker Build
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: build
        run: docker build --output=package .

      - name: prepare-release
        id: artifact
        run: |
          ARTIFACT_DIR="release-candidate-$(jq -r '.version' package.json)"
          echo "dir=$ARTIFACT_DIR" >> "$GITHUB_OUTPUT"
          mkdir $ARTIFACT_DIR
          mv package/electron-secure-defaults* $ARTIFACT_DIR

      - name: upload
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.artifact.outputs.dir }}
          path: ${{ steps.artifact.outputs.dir }}
